###please run with "dev" environment

###credentials

###good weather with correct credentials
POST http://{{host}}:{{port}}/credentials
Content-Type: application/json

{
  "email": "yibingdoe@hotmail.com",
  "password": "haha12"
}
> {% client.global.set("auth_token", response.body.token);
 client.test("log in good weather",function (){
     client.assert(response.status==202,"Response status is not 202");
 });
 %}



###bad weather with wrong credentials
POST http://{{host}}:{{port}}/credentials
Content-Type: application/json

{
  "email": "yibingdoe@hotmail.com",
  "password": "haha123"
}
> {%
 client.test("log in bad weather",function (){
     client.assert(response.status==401,"Response status is not 401");
 });
 %}





###bids

###Good weather tests
###get all bids
GET http://{{host}}:{{port}}/bids
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==200,"Response status is not 200");
     client.assert(response.body.length==7,"Incorrect number of items in the list");
 });
 %}


###get one bid by id 2
GET http://{{host}}:{{port}}/bids/2
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==202,"Response status is not 202");
 });
 %}

### Post a new bid
POST http://{{host}}:{{port}}/bids
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": 30,
  "price": 5,
  "placedByUserId": 3,
  "forBikeId": 3
}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==201,"Response status is not 201");
 });
 %}

###delete bid at id 2
DELETE http://{{host}}:{{port}}/bids/2
Authorization: Bearer {{auth_token}}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==204,"Response status is not 204");
 });
 %}

###bad weather tests
###get all bids but authorization token is in correct
GET http://{{host}}:{{port}}/bids
Accept: application/json
Authorization: Bearer jdsjofosfjowoowf

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==401,"Response status is not 401");
 });
 %}

###get one bid by id 333 which does not exist
GET http://{{host}}:{{port}}/bids/333
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==404,"Response status is not 404");
 });
 %}




###users

###get all users
http://{{host}}:{{port}}/users
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==200,"Response status is not 200");
     client.assert(response.body.length==3,"Number of items in the list is incorrect")
 });
 %}

###get one user by id 2
GET http://{{host}}:{{port}}/users/2
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==202,"Response status is not 202");
 });
 %}

###create a user
POST http://{{host}}:{{port}}/users
Authorization: Bearer {{auth_token}}
Content-Type:application/json

{
  "name": "Gerralt",
  "email": "gerralt@gmail.com",
  "passwordHashValue": "haha12"
}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==201,"Response status is not 201");
 });
 %}

###delete a user on id 1
DELETE http://{{host}}:{{port}}/users/1
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==204,"Response status is not 204");
 });
 %}

###bad weather test
###get all users but the token is incorrect
http://{{host}}:{{port}}/users
Accept: application/json
Authorization: Bearer jjsiofjso

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==401,"Response status is not 401");
 });
 %}

###get one user by id 555 which does not exist
GET http://{{host}}:{{port}}/users/555
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==404,"Response status is not 404");
 });
 %}

###create a user but the password is empty
POST http://{{host}}:{{port}}/users
Authorization: Bearer {{auth_token}}
Content-Type:application/json

{
  "name": "Gerralt",
  "email": "gerralt@gmail.com",
  "passwordHashValue": ""
}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==400,"Response status is not 400");
 });
 %}

###delete a user on an id that doesnt exist e.g. 89
DELETE http://{{host}}:{{port}}/clients/89
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==404,"Response status is not 404");
 });
 %}




###bikes

###get all bikes
GET http://{{host}}:{{port}}/bikes
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==200,"Response status is not 200");
     client.assert(response.body.length==10,"Number of items in the list is incorrect");
 });
 %}

###get all bikes filtered on frame type and frame height
GET http://{{host}}:{{port}}/bikes?frameType=Diamond&frameHeightInCm=53
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==200,"Response status is not 200");
     client.assert(response.body.length=2,"Number of items in the list is incorrect");
 });
 %}

###search bikes on keyword "Ga"
GET http://{{host}}:{{port}}/bikes/search?keyword=Ga
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==200,"Response status is not 200");
     client.assert(response.body.length=2,"Number of items in the list is incorrect");
 });
 %}

###get all bikes filtered on brand
GET http://{{host}}:{{port}}/bikes?brand=Gazelle
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==200,"Response status is not 200");
     client.assert(response.body.length=2,"Number of items in the list is incorrect");
 });
 %}

###get one bike by id 1
GET http://{{host}}:{{port}}/bikes/1
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==202,"Response status is not 202");
 });
 %}

###create a bike
POST http://{{host}}:{{port}}/bikes
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "brand": "Gazelle",
  "frameType": "Diamond",
  "frameHeightInCm": "55",
  "endingDate": "2023-04-25"
}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==201,"Response status is not 201");
 });
 %}

###modify a bike
PUT http://{{host}}:{{port}}/bikes
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": 10,
  "brand": "Gazelle",
  "frameType": "Diamond",
  "frameHeightInCm": "55"
}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==202,"Response status is not 202");
 });
 %}

###delete a bike on id 2
DELETE http://{{host}}:{{port}}/bikes/2
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==204,"Response status is not 204");
 });
 %}



###bad weather
###get all bikes but the token is incorrect
GET http://{{host}}:{{port}}/bikes
Accept: application/json
Authorization: Bearer fgdfdgd

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==401,"Response status is not 401");
 });
 %}

###get all bikes filtered on frame type and frame height but the frame type does not exist
GET http://{{host}}:{{port}}/bikes?frameType=Diand&frameHeightInCm=53
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==200,"Response status is not 200");
     client.assert(response.body.length==0,"number of items in the list is incorrect")
 });
 %}

###get all bikes filtered on brand but the brand does not exist
GET http://{{host}}:{{port}}/bikes?brand=Gazelleah
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==200,"Response status is not 200");
     client.assert(response.body.length==0,"number of items in the list is incorrect")
 });
 %}

###get one bike by id that does not exist such as 88
GET http://{{host}}:{{port}}/bikes/88
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==404,"Response status is not 404");
 });
 %}

###create a bike but the some key in the body is empty
POST http://{{host}}:{{port}}/bikes
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "brand": "Gazelle",
  "frameType": "",
  "frameHeightInCm": "55",
  "endingDate": "2023-04-25"
}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==404,"Response status is not 404");
 });
 %}


###modify a bike but the id does not exist
PUT http://{{host}}:{{port}}/bikes
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": 1022,
  "brand": "Gazelle",
  "frameType": "Diamond",
  "frameHeightInCm": "55"
}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==400,"Response status is not 400");
 });
 %}

###delete a bike on id that does not exist such as 444
DELETE http://{{host}}:{{port}}/bikes/444
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
 client.test("Requst excuted successfully",function (){
     client.assert(response.status==404,"Response status is not 404");
 });
 %}





